name: CI
on: [push]

jobs:
  
  frontend_build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install deps
        run: cd frontend && npm install
      - name: Build and test front 
        run: cd frontend && npm test
