name: CI
on: [push]

jobs:
  backend_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Backend build
        run: ./gradlew build
      - name: Backend test
        run: ./gradlew test

  frontend_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Install deps
        run: npm Install
      - name: Build and test front 
        run: npm test
