name: CI
on: push

jobs:
  
  backend_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Backend build
        run: cd backend && ./gradlew build
      - name: Backend test
        run: cd backend && ./gradlew test
  
  frontend_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install deps
        run: cd frontend && npm install
      - name: Build and test front 
        run: cd frontend && npm test
  
  run_linters:
   runs-on: ubuntu-latest

   steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: cd frontend && npm install

      - name: run ESLint
        run: cd frontend && npm run lint
        
